/* Forge — journal → AI analysis → quests with AI-generated rewards.
   Core loop from the video: journal, get analyzed, get a quest.
   Rewards per quest: XP + attribute points (focus/discipline/…) + coins,
   all generated by the AI based on the quest itself. State in localStorage. */
const XP = { side: 10, minor: 25, major: 50, epic: 100 };
const COINS = { side: 5, minor: 10, major: 25, epic: 50 };
const TITLES = [[1, 'Novice'], [3, 'Apprentice'], [5, 'Knight'], [8, 'Veteran'], [12, 'Champion'], [16, 'Legend']];
const COACH_SYS = `You are the Forge Quest-Master, a terse RPG mentor. Rules:
- Give quests as short "- title" lines when the user asks for tasks or a plan.
- Keep replies under 120 words. No fluff, no purple prose.
- Celebrate completions briefly. Push back on excuses, kindly but firmly.`;
const FORGE_SYS = `You turn a personal journal entry into RPG quests. Output ONLY quest blocks, one per line, exactly this shape:
- title [rank] :: one-line description :: step 1; step 2; step 3 :: attr points; attr points :: Nc
Rules: rank is side, minor, major or epic (mostly minor/side). 3-6 quests. Steps are short concrete instructions (2-4). Attributes chosen from focus, discipline, creativity, energy, courage, wisdom — 1-5 points each, matching what the quest builds. N is coins 5-50. No other text.`;

const store = {
  load() { try { return JSON.parse(localStorage.getItem('forge') || '{}'); } catch { return {}; } },
  save(s) { localStorage.setItem('forge', JSON.stringify(s)); },
};
let S = Object.assign({ xp: 0, coins: 0, attrs: {}, quests: [], streak: 0, lastDay: null, journal: [], autoForge: false, orKey: '', orModel: 'meta-llama/llama-3.3-70b-instruct:free', nimKey: '', nimModel: 'meta/llama-3.3-70b-instruct' }, store.load());
const save = () => store.save(S);
const today = () => new Date().toISOString().slice(0, 10);
const $ = (id) => document.getElementById(id);
const esc = (s) => s;

function level() { return Math.floor(Math.sqrt(S.xp / 100)) + 1; }
function levelBase(l) { return 100 * (l - 1) * (l - 1); }
function titleFor(l) { let t = TITLES[0][1]; for (const [lv, name] of TITLES) if (l >= lv) t = name; return t; }

function toast(msg) {
  const el = $('toast');
  el.textContent = msg; el.hidden = false;
  clearTimeout(el._t);
  el._t = setTimeout(() => { el.hidden = true; }, 2800);
}

function topAttrs(n = 3) {
  return Object.entries(S.attrs).sort((a, b) => b[1] - a[1]).slice(0, n);
}

function render() {
  const l = level(), base = levelBase(l), next = levelBase(l + 1);
  $('charTitle').textContent = titleFor(l);
  $('levelBadge').textContent = 'Lv ' + l;
  $('xpText').textContent = S.xp + ' XP · ' + S.coins + ' coins';
  $('xpFill').style.width = Math.min(100, ((S.xp - base) / (next - base)) * 100) + '%';
  const open = S.quests.filter((q) => !q.done), done = S.quests.filter((q) => q.done);
  $('streakNum').textContent = S.streak;
  $('doneNum').textContent = done.length;
  $('openNum').textContent = open.length;
  const ta = topAttrs().map(([k, v]) => `${k} ${v}`).join(' · ') || 'No attributes yet — complete a quest';
  $('attrLine').textContent = ta;

  $('activeList').innerHTML = open.length ? '' : '<li class="empty">No active quests. Journal below and let the AI forge some — or add one manually.</li>';
  for (const q of open) $('activeList').appendChild(questNode(q, false));
  $('doneList').innerHTML = done.length ? '' : '<li class="empty">Nothing completed yet. Your legend starts with one quest.</li>';
  for (const q of [...done].reverse().slice(0, 20)) $('doneList').appendChild(questNode(q, true));
}

function rewardText(q) {
  const parts = [`+${XP[q.rank]} XP`, `+${COINS[q.rank]} coins`];
  for (const [k, v] of Object.entries(q.attrs || {})) parts.push(`+${v} ${k}`);
  return parts.join(' · ');
}

function questNode(q, isDone) {
  const li = document.createElement('li');
  li.className = 'quest' + (isDone ? ' is-done' : '');
  const head = document.createElement('div');
  head.className = 'quest-head';
  head.innerHTML = `<span class="rank">${q.rank}</span>`;
  const t = document.createElement('span');
  t.className = 'title'; t.textContent = q.title;
  head.appendChild(t);
  const xp = document.createElement('span');
  xp.className = 'xp'; xp.textContent = `+${XP[q.rank]} XP`;
  head.appendChild(xp);
  li.appendChild(head);
  if (q.desc || (q.steps && q.steps.length) || q.attrs) {
    const det = document.createElement('div');
    det.className = 'quest-detail';
    det.hidden = true;
    if (q.desc) { const d = document.createElement('p'); d.className = 'qdesc'; d.textContent = q.desc; det.appendChild(d); }
    if (q.steps && q.steps.length) {
      const ol = document.createElement('ol');
      ol.className = 'qsteps';
      q.steps.forEach((s) => { const sli = document.createElement('li'); sli.textContent = s; ol.appendChild(sli); });
      det.appendChild(ol);
    }
    const r = document.createElement('p');
    r.className = 'qrewards'; r.textContent = 'Rewards: ' + rewardText(q);
    det.appendChild(r);
    li.appendChild(det);
    head.style.cursor = 'pointer';
    head.onclick = () => { det.hidden = !det.hidden; };
  }
  if (!isDone) {
    const btn = document.createElement('button');
    btn.className = 'btn btn-gold btn-sm'; btn.textContent = 'Complete';
    btn.onclick = (e) => { e.stopPropagation(); completeQuest(q.id); };
    li.appendChild(btn);
  }
  return li;
}

function newQuest(o) {
  return { id: Date.now() + '' + Math.floor(Math.random() * 1e4), title: o.title, rank: o.rank || 'minor', desc: o.desc || '', steps: o.steps || [], attrs: o.attrs || {}, done: false, created: today() };
}
function addQuest(title, rank = 'minor') { S.quests.push(newQuest({ title, rank })); save(); render(); }
function addQuestSilent(o) { S.quests.push(newQuest(o)); }

function completeQuest(id) {
  const q = S.quests.find((x) => x.id === id);
  if (!q || q.done) return;
  const before = level();
  q.done = true; q.doneDay = today();
  S.xp += XP[q.rank];
  S.coins += COINS[q.rank];
  for (const [k, v] of Object.entries(q.attrs || {})) S.attrs[k] = (S.attrs[k] || 0) + v;
  touchDay();
  save(); render();
  const after = level();
  toast(after > before ? `LEVEL UP! Lv ${after} ${titleFor(after)} — ${rewardText(q)}` : `Quest complete — ${rewardText(q)}`);
}

function touchDay() {
  const t = today();
  if (S.lastDay === t) return;
  const y = new Date(Date.now() - 864e5).toISOString().slice(0, 10);
  S.streak = S.lastDay === y ? S.streak + 1 : 1;
  S.lastDay = t;
}

$('questForm').onsubmit = (e) => {
  e.preventDefault();
  const t = $('questTitle').value.trim();
  if (!t) return;
  addQuest(t, $('questRank').value);
  $('questTitle').value = '';
  toast('Quest added. Go earn it.');
};

$('checkinBtn').onclick = () => {
  touchDay(); save(); render();
  toast(`Checked in — ${S.streak}-day streak`);
};

// ---- Drawers ----
function toggle(id, show) { $(id).hidden = show === undefined ? !$(id).hidden : !show; }
$('coachBtn').onclick = () => toggle('coachDrawer', true);
$('coachClose').onclick = () => toggle('coachDrawer', false);
$('settingsBtn').onclick = () => { syncSettings(); toggle('settingsDrawer', true); };
$('settingsClose').onclick = () => toggle('settingsDrawer', false);

function syncSettings() {
  $('orKey').value = S.orKey; $('orModel').value = S.orModel;
  $('nimKey').value = S.nimKey; $('nimModel').value = S.nimModel;
}
$('saveSettings').onclick = () => {
  S.orKey = $('orKey').value.trim(); S.orModel = $('orModel').value.trim() || S.orModel;
  S.nimKey = $('nimKey').value.trim(); S.nimModel = $('nimModel').value.trim() || S.nimModel;
  save(); toggle('settingsDrawer', false);
  toast('Settings saved');
};
$('resetAll').onclick = () => {
  if (!confirm('Wipe all quests, XP, coins and streaks?')) return;
  const keep = { orKey: S.orKey, orModel: S.orModel, nimKey: S.nimKey, nimModel: S.nimModel, journal: S.journal, autoForge: S.autoForge };
  S = Object.assign({ xp: 0, coins: 0, attrs: {}, quests: [], streak: 0, lastDay: null }, keep);
  save(); render(); renderJournal(); toggle('settingsDrawer', false);
};

// ---- AI Coach: OpenRouter primary, NVIDIA NIM backup ----
function chatAdd(role, text) {
  const log = $('chatLog');
  const div = document.createElement('div');
  div.className = 'msg ' + role;
  div.textContent = text;
  if (role === 'coach') {
    const lines = text.split('\n').filter((l) => l.trim().startsWith('- '));
    if (lines.length) {
      const b = document.createElement('button');
      b.className = 'addq'; b.textContent = `＋ Add ${lines.length} as quests`;
      b.onclick = () => { lines.forEach((l) => addQuest(l.replace(/^-+\s*/, '').slice(0, 120))); toast(lines.length + ' quests added'); };
      div.appendChild(b);
    }
  }
  log.appendChild(div);
  log.scrollTop = log.scrollHeight;
}

async function callChat(url, key, model, messages) {
  const r = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + key },
    body: JSON.stringify({ model, messages, max_tokens: 600, temperature: 0.8 }),
  });
  if (!r.ok) throw new Error('HTTP ' + r.status);
  const d = await r.json();
  const c = d.choices && d.choices[0] && d.choices[0].message && d.choices[0].message.content;
  if (!c) throw new Error('empty reply');
  return c;
}

const history = [];
$('chatForm').onsubmit = async (e) => {
  e.preventDefault();
  const input = $('chatInput').value.trim();
  if (!input) return;
  $('chatInput').value = '';
  chatAdd('user', input);
  history.push({ role: 'user', content: input });
  const msgs = [{ role: 'system', content: COACH_SYS + `\nPlayer: Lv ${level()} ${titleFor(level())}, ${S.xp} XP, ${S.coins} coins, ${S.streak}-day streak. Top: ${topAttrs().map(([k, v]) => k + ' ' + v).join(', ') || 'none'}.` }, ...history.slice(-10)];
  chatAdd('coach', '…');
  const pending = $('chatLog').lastChild;
  const fail = (m) => { pending.textContent = m; };
  if (S.orKey) {
    try {
      const reply = await callChat('https://openrouter.ai/api/v1/chat/completions', S.orKey, S.orModel, msgs);
      pending.remove();
      chatAdd('coach', reply);
      history.push({ role: 'assistant', content: reply });
      return;
    } catch (err) { /* fall through to NIM */ }
  }
  if (S.nimKey) {
    try {
      const reply = await callChat('https://integrate.api.nvidia.com/v1/chat/completions', S.nimKey, S.nimModel, msgs);
      pending.remove();
      chatAdd('coach', reply);
      history.push({ role: 'assistant', content: reply });
      return;
    } catch (err) { fail('Both providers failed. Check keys in Settings.'); return; }
  }
  fail('Add your OpenRouter key in Settings first (NVIDIA NIM works as backup).');
};

// ---- Journal → autonomous quest forging ----
function parseForge(text) {
  const out = [];
  for (const line of text.split('\n')) {
    const m = line.trim().match(/^[-*•]\s*(.+)$/);
    if (!m) continue;
    const parts = m[1].split('::').map((s) => s.trim());
    const tm = parts[0].match(/^(.+?)(?:\s*\[(side|minor|major|epic)\])?\s*$/i);
    if (!tm) continue;
    const q = { title: tm[1].slice(0, 120), rank: (tm[2] || 'minor').toLowerCase(), desc: '', steps: [], attrs: {}, coins: 0 };
    if (parts[1]) q.desc = parts[1].slice(0, 200);
    if (parts[2]) q.steps = parts[2].split(';').map((s) => s.trim().slice(0, 120)).filter(Boolean).slice(0, 5);
    if (parts[3]) {
      for (const a of parts[3].split(/[;,]/)) {
        const am = a.trim().match(/^([a-z]+)\s+(\d+)$/i);
        if (am) q.attrs[am[1].toLowerCase()] = Math.min(5, parseInt(am[2], 10));
      }
    }
    if (parts[4]) { const cm = parts[4].match(/(\d+)/); if (cm) q.coins = Math.min(50, parseInt(cm[1], 10)); }
    if (!q.coins) q.coins = COINS[q.rank];
    out.push(q);
  }
  return out.slice(0, 8);
}

let editId = null;
function renderJournal() {
  const list = $('journalList');
  list.innerHTML = S.journal.length ? '' : '<li>No entries yet. Write your first one above.</li>';
  for (const j of [...S.journal].reverse().slice(0, 7)) {
    const li = document.createElement('li');
    const strong = document.createElement('strong');
    strong.textContent = j.day + (j.forged > 0 ? ` · forged ${j.forged} quests` : '') + (editId === j.id ? ' · editing' : '');
    li.appendChild(strong);
    li.appendChild(document.createTextNode(' — ' + (j.text.length > 140 ? j.text.slice(0, 140) + '…' : j.text)));
    li.style.cursor = 'pointer';
    li.title = 'Tap to read / edit';
    li.onclick = () => {
      if (editId === j.id) { editId = null; $('journalText').value = ''; $('forgeBtn').textContent = 'Forge my quests'; }
      else { editId = j.id; $('journalText').value = j.text; $('forgeBtn').textContent = 'Save + re-forge'; $('journalText').focus(); }
      renderJournal();
    };
    list.appendChild(li);
  }
  $('autoForge').checked = !!S.autoForge;
}

async function forgeFromJournal(silent) {
  const text = $('journalText').value.trim();
  if (!text) { if (!silent) toast('Write something in your journal first'); return; }
  if (!S.orKey && !S.nimKey) { if (!silent) toast('Add your OpenRouter key in Settings first'); return; }
  if (!silent) toast('Reading your journal…');
  const msgs = [
    { role: 'system', content: FORGE_SYS },
    { role: 'user', content: `Player: Lv ${level()} ${titleFor(level())}, top attributes: ${topAttrs().map(([k, v]) => k + ' ' + v).join(', ') || 'none'}.\nJournal:\n${text.slice(0, 2000)}` },
  ];
  let quests = [];
  if (S.orKey) {
    try {
      quests = parseForge(await callChat('https://openrouter.ai/api/v1/chat/completions', S.orKey, S.orModel, msgs));
    } catch (err) { /* fall through to NIM */ }
  }
  if (!quests.length && S.nimKey) {
    try {
      quests = parseForge(await callChat('https://integrate.api.nvidia.com/v1/chat/completions', S.nimKey, S.nimModel, msgs));
    } catch (err) { /* fall through */ }
  }
  if (!quests.length) { if (!silent) toast('The forge is cold — providers failed. Check keys.'); return; }
  if (editId) {
    const j = S.journal.find((x) => x.id === editId);
    if (j) { j.text = text.slice(0, 2000); j.forged = quests.length; }
    editId = null;
    $('forgeBtn').textContent = 'Forge my quests';
  } else {
    S.journal.push({ id: Date.now() + '', day: today(), text: text.slice(0, 2000), forged: quests.length });
  }
  quests.forEach(addQuestSilent);
  touchDay();
  save(); render(); renderJournal();
  $('journalText').value = '';
  toast(`Forged ${quests.length} quests — tap any quest for steps + rewards`);
}

$('forgeBtn').onclick = () => forgeFromJournal(false);
$('autoForge').onchange = (e) => { S.autoForge = e.target.checked; save(); };

render();
renderJournal();
if (!S.quests.length) chatAdd('coach', 'Welcome to the Forge. Journal below and I will forge your quests — or tell me one goal directly.');
// Autonomous loop: new day + auto-forge on + an unforged older entry → forge it
(function autoLoop() {
  if (!S.autoForge || (!S.orKey && !S.nimKey)) return;
  const t = today();
  const pending = [...S.journal].reverse().find((j) => j.day !== t && !j.forged && j.text);
  if (!pending) return;
  pending.forged = -1;
  $('journalText').value = pending.text;
  editId = pending.id;
  forgeFromJournal(true);
})();
